{% set name = "navi" %}
{% set version = "2.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/denisidoro/navi/archive/v{{ version }}.tar.gz
  sha256: 579a72814e7ba07dae697a58dc13b0f7d853532ec07229aff07a11e5828f3799

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - zlib
  run:
    - fzf

test:
  commands:
    - navi --help

about:
  home: https://github.com/denisidoro/navi
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Interactive cheatsheet tool for the command-line
  dev_url: https://github.com/denisidoro/navi

extra:
  recipe-maintainers:
    - danielnachun
